# Generated by Django 5.2 on 2025-06-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"permissions": [("can_view_users", "Can view users"), ("can_block_user", "Can block users")]},
        ),
    ]
