# Generated by Django 5.2 on 2025-06-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
