# Generated by Django 5.2 on 2025-06-25 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0002_alter_mailing_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
