# Generated by Django 5.2 on 2025-06-30 03:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0006_mailing_owner_message_owner_recipient_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sendingattempt",
            name="recipient",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="newsletters.recipient"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sendingattempt",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
