# Generated by Django 5.2 on 2025-06-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0007_sendingattempt_recipient_sendingattempt_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_mailing", "Can view mailing"),
                    ("can_edit_mailing", "Can edit mailing"),
                    ("can_delete_mailing", "Can delete mailing"),
                    ("can_disable_mailing", "Can_disable_mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
