# Generated by Django 5.2 on 2025-06-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0008_alter_mailing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
