# Generated by Django 5.2 on 2025-06-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0009_mailing_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
