# Generated by Django 5.2 on 2025-07-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0010_mailing_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(max_length=10),
        ),
    ]
