# Generated by Django 5.2 on 2025-07-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0011_alter_mailing_start_time_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(default="Создана", max_length=10),
        ),
        migrations.AlterField(
            model_name="sendingattempt",
            name="status",
            field=models.CharField(default="Успешно", max_length=10),
        ),
    ]
