# Generated by Django 5.2 on 2025-07-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0012_alter_mailing_status_alter_sendingattempt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("created", "Создана"), ("started", "Запущена"), ("finished", "Завершена")],
                default="Создана",
                max_length=10,
            ),
        ),
    ]
