from django.urls import path
from .views import (
    statistics_view,
    MailingCreateView,
    MailingListView,
    MailingEditView,
    MailingDeleteView,
    MessageListView,
    MessageDetailView,
    MessageCreateView,
    MessageEditView,
    MessageDeleteView,
    MailingDetailView,
    RecipientCreateView,
    RecipientListView,
    RecipientDetailView,
    RecipientEditView,
    RecipientDeleteView,
    task_detail,
)

urlpatterns = [
    path("statistics/", statistics_view, name="statistics"),
    path("recipients/", RecipientListView.as_view(), name="recipient_list"),
    path("recipients/create/", RecipientCreateView.as_view(), name="create_recipient"),
    path("recipients/<int:pk>/", RecipientDetailView.as_view(), name="recipient_detail"),
    path("recipients/edit/<int:pk>/", RecipientEditView.as_view(), name="edit_recipient"),
    path("recipients/delete/<int:pk>/", RecipientDeleteView.as_view(), name="delete_recipient"),
    path("messages/", MessageListView.as_view(), name="message_list"),
    path("messages/create/", MessageCreateView.as_view(), name="create_message"),
    path("messages/<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path("messages/edit/<int:pk>/", MessageEditView.as_view(), name="edit_message"),
    path("messages/delete/<int:pk>/", MessageDeleteView.as_view(), name="delete_message"),
    path("mailings/create/", MailingCreateView.as_view(), name="create_mailing"),
    path("mailings/", MailingListView.as_view(), name="mailing_list"),
    path("mailings/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("mailings/edit/<int:pk>/", MailingEditView.as_view(), name="edit_mailing"),
    path("mailings/delete/<int:pk>/", MailingDeleteView.as_view(), name="delete_mailing"),
    path(
        "mailings/send/<int:pk>/",
        lambda request, pk: __import__("newsletters.views").send_mailing(request, pk),
        name="send_mailing",
    ),
    path("task_detail/", task_detail, name="task_detail"),
]
