# Generated by Django 5.2 on 2025-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "permissions": (("can_manage_blog", "Can manage blog posts"),),
                "verbose_name": "Блоговая запись",
                "verbose_name_plural": "Блоговые записи",
            },
        ),
        migrations.AddField(
            model_name="blogpost",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
